[[main]]
name = "Home"
url = "/"
weight = 10

[[main]]
name = "Blog"
url = "/posts"
weight = 20

[[main]]
name = "Cheatsheet"
url = "/cheatsheets"
weight = 30

[[main]]
name = "Author"
url = "https://armoghan.netlify.app"
weight = 40

[[main]]
name = "Contact"
url = "https://armoghan.netlify.app/contact"
weight = 50

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.
[[footer]]
name = "Tags"
url = "/tags"
weight = 10

[[footer]]
name = "Categories"
url = "/categories"
weight = 20

[[footer]]
name = "Series"
url = "/series"
weight = 30

[[footer]]
name = "Newsletter"
url = "https://armoghan-blogs.ck.page/"
weight = 40
