[[main]]
name = "Home"
pageRef = "/"
weight = 10

[[main]]
name = "Blog"
pageRef = "posts"
weight = 20

[[main]]
name = "Cheatsheet"
pageRef = "cheatsheets"
weight = 30

[[main]]
name = "Author"
url = "https://armoghan.netlify.app"
weight = 40

[[main]]
name = "Contact"
url = "https://armoghan.netlify.app/contact"
weight = 50

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.
[[footer]]
name = "Tags"
pageRef = "tags"
weight = 10

[[footer]]
name = "Categories"
pageRef = "categories"
weight = 20
