[[main]]
name = "Home"
url = "https://armoghan-blogs-2.netlify.app/"
weight = 10

[[main]]
name = "Blog"
url = "https://armoghan-blogs-2.netlify.app/posts"
weight = 20

[[main]]
name = "Cheatsheet"
url = "https://armoghan-blogs-2.netlify.app/cheatsheets"
weight = 30

[[main]]
name = "Author"
url = "https://armoghan.netlify.app"
weight = 40

[[main]]
name = "Contact"
url = "https://armoghan.netlify.app/contact"
weight = 50

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.
[[footer]]
name = "Tags"
url = "https://armoghan-blogs-2.netlify.app/tags"
weight = 10

[[footer]]
name = "Categories"
url = "https://armoghan-blogs-2.netlify.app/categories"
weight = 20
