colorScheme = "blowfish"
defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
mainSections = ["posts", "categories"]
disableImageOptimization = true
defaultBackgroundImage = "img/background.jpeg" # used as default for background images
defaultFeaturedImage = "/img/ocebackground-altan.jpeg"
highlightCurrentMenuArea = true
smartTOC = true

[header]
layout = "fixed-fill-blur" # valid options: basic, fixed, fixed-fill, fixed-fill-blur

[footer]
showMenu = true
showCopyright = true
showThemeAttribution = true
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "background" # valid options: page, profile, hero, card, background, custom
# homepageImage = "homepage.jpeg" # used in: hero, and card
showRecent = true
showRecentItems = 6
showMoreLink = true
showMoreLinkDest = "/posts"
cardView = true
cardViewScreenWidth = false
layoutBackgroundBlur = true # only used when layout equals background

[article]
showDate = true
showViews = true
showLikes = true
showDateUpdated = true
showAuthor = true
showHero = true
heroStyle = "thumbAndBackground" # valid options: basic, big, background, thumbAndBackground
layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showRelatedContent = true
relatedContentLimit = 3
showTaxonomies = true
showAuthorsBadges = true
showWordCount = true
showSummary = true
showComments = false
sharingLinks = [
    "linkedin",
    "twitter",
    "reddit",
    "pinterest",
    "facebook",
    "email",
    "whatsapp",
    "telegram"
]

[list]
showHero = true
heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
showBreadcrumbs = true
showSummary = true
showViews = false
showLikes = false
showTableOfContents = true
showCards = true
groupByYear = true
cardView = true
cardViewScreenWidth = false
constrainItemsWidth = false

[sitemap]
excludedKinds = ["taxonomy", "term"]

[taxonomy]
showTermCount = true
showHero = true
heroStyle = "thumbAndBackground" # valid options: basic, big, background, thumbAndBackground
showBreadcrumbs = true
showViews = true
showLikes = true
showTableOfContents = true
cardView = true

[term]
showHero = true
heroStyle = "thumbAndBackground" # valid options: basic, big, background, thumbAndBackground
showBreadcrumbs = false
showViews = true
showLikes = true
showTableOfContents = true
groupByYear = true
cardView = true
cardViewScreenWidth = false

[firebase]
apiKey = "AIzaSyD6Gnzi84m8f9VpFnz3coDKI9qYkRMeRcg"
authDomain = "armoghan-blogs-2.firebaseapp.com"
projectId = "armoghan-blogs-2"
storageBucket = "armoghan-blogs-2.appspot.com"
messagingSenderId = "212567487610"
appId = "1:212567487610:web:f7df8015657173f0b937c3"
measurementId = "G-HJ48W25V96"

[fathomAnalytics]

# site = "ABC12345"
# domain = "llama.yoursite.com"
[buymeacoffee]

# identifier = ""
# globalWidget = true
# globalWidgetMessage = "Hello"
# globalWidgetColor = "#FFDD00"
# globalWidgetPosition = "Right"
[verification]
# google = ""
# bing = ""
# pinterest = ""
# yandex = ""
