colorScheme = "blowfish"
defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = true
# mainSections = ["section1", "section2"]
# robots = ""
disableImageOptimization = true
# defaultBackgroundImage = "IMAGE.jpg" # used as default for background images
# defaultFeaturedImage = "IMAGE.jpg" # used as default for featured images in all articles
highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = true

[header]
layout = "fixed-fill-blur" # valid options: basic, fixed, fixed-fill, fixed-fill-blur

[footer]
showMenu = true
showCopyright = false
showThemeAttribution = false
showAppearanceSwitcher = true
showScrollToTop = true

[homepage]
layout = "background" # valid options: page, profile, hero, card, background, custom
# homepageImage = "homepage.jpeg" # used in: hero, and card
showRecent = true
showRecentItems = 3
showMoreLink = true
showMoreLinkDest = "/posts"
cardView = true
cardViewScreenWidth = false
layoutBackgroundBlur = true # only used when layout equals background

[article]
showDate = true
showViews = true
showLikes = true
showDateUpdated = true
showAuthor = true
showHero = true
heroStyle = "thumbAndBackground" # valid options: basic, big, background, thumbAndBackground
layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
showBreadcrumbs = true
showDraftLabel = true
showEdit = false
editAppendPath = true
seriesOpened = false
showHeadingAnchors = true
showPagination = true
invertPagination = false
showReadingTime = true
showTableOfContents = true
showRelatedContent = true
relatedContentLimit = 5
showTaxonomies = true
showAuthorsBadges = true
showWordCount = true
showSummary = true
showComments = true
sharingLinks = [
    "linkedin",
    "twitter",
    "reddit",
    "pinterest",
    "facebook",
    "email",
    "whatsapp",
    "telegram"
]

[list]
showHero = true
heroStyle = "thumbAndBackground" # valid options: basic, big, background, thumbAndBackground
layoutBackgroundBlur = true # only used when heroStyle equals background or thumbAndBackground
layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
showBreadcrumbs = true
showSummary = true
showViews = false
showLikes = false
showTableOfContents = true
showCards = true
groupByYear = true
cardView = true
cardViewScreenWidth = false
constrainItemsWidth = false

[sitemap]
excludedKinds = ["taxonomy", "term"]

[taxonomy]
showTermCount = true
showHero = true
heroStyle = "thumbAndBackground" # valid options: basic, big, background, thumbAndBackground
showBreadcrumbs = true
showViews = true
showLikes = true
showTableOfContents = true
cardView = true

[term]
showHero = true
heroStyle = "thumbAndBackground" # valid options: basic, big, background, thumbAndBackground
showBreadcrumbs = false
showViews = true
showLikes = true
showTableOfContents = true
groupByYear = true
cardView = true
cardViewScreenWidth = false

[firebase]
apiKey = "AIzaSyCT-ZbvUmG1Wcj3FG-rbq2wMUoj8c7grkk"
authDomain = "armoghan-blogs.firebaseapp.com"
projectId = "armoghan-blogs"
storageBucket = "armoghan-blogs.appspot.com"
messagingSenderId = "15885828986"
appId = "1:15885828986:web:52c5afcb1ce8778437ccc3"
measurementId = "G-EH3T9VZ3DM"

[fathomAnalytics]

# site = "ABC12345"
# domain = "llama.yoursite.com"
[buymeacoffee]

# identifier = ""
# globalWidget = true
# globalWidgetMessage = "Hello"
# globalWidgetColor = "#FFDD00"
# globalWidgetPosition = "Right"
[verification]
# google = ""
# bing = ""
# pinterest = ""
# yandex = ""
