[build]
command = "hugo  --minify -D "
publish = "public"

[build.environment]
HUGO_THEMESDIR = "../.."
HUGO_THEME = "repo"

[context.production.environment]
HUGO_VERSION = "0.104.1"
HUGO_ENV = "production"
