[build]
command = "cd Armoghan-Blogs && hugo  --minify -D "
publish = "Armoghan-Blogs/public"

[build.environment]
HUGO_THEMESDIR = "../.."
HUGO_THEME = "repo"

[context.production.environment]
HUGO_VERSION = "0.104.1"
HUGO_ENV = "production"
